/*
$('').click(function(){
  socket.emit('',{});
  $('').val("");
});
$('').click(function(){
  socket.emit('',{});
  $('').val("");
});
$('').click(function(){
  socket.emit('',{});
  $('').val("");
});
$('').click(function(){
  socket.emit('',{});
  $('').val("");
});
*/
